# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/dora.yaml.j2

dora:
  fullnameOverride: dora
  image:
    repository: ethpandaops/dora
    tag: master
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 2Gi
  ingress:
    enabled: true
    className: nginx
    hosts:
      - host: dora.devnet-0.giangho.pro
        paths:
          - path: /
            pathType: Prefix

  name: devnet-0
  configPath: "https://config.devnet-0.giangho.pro/cl/config.yaml"
  validatorNamesInventory: "https://config.devnet-0.giangho.pro/api/v1/nodes/validator-ranges"
  proxyCount: 2
  extraEnv:
   - name: FRONTEND_PPROF
     value: "true"
   
  postgresql:
    name: "dora-postgresql"
    fullnameOverride: "dora-postgresql"
  
  endpoints:
  # Rpc
  - url: http://teku-geth-001:5052
    name: rpc-teku-geth-001
    archive: true
    priority: 1
  - url: https://bn.bootnode-1.devnet-0.giangho.pro
    name: bootnode-1
    priority: -1
  - url: https://bn.lighthouse-geth-1.devnet-0.giangho.pro
    name: lighthouse-geth-1
    priority: -1
    archive: true
  - url: https://bn.prysm-geth-1.devnet-0.giangho.pro
    name: prysm-geth-1
    priority: -1
