secret_zerossl:
    ACME_EAB_KID: ENC[AES256_GCM,data:GuUDMwy/ZdMIZAVkh+oXLkAR+zgooA==,iv:jDGAmCxlsNUg6VkFNucq+6nXxK2a4rhwVR3ZIEUERA0=,tag:Cp4QuEfLx42dlVRbh7ICOA==,type:str]
    ACME_EAB_HMAC_KEY: ENC[AES256_GCM,data:TCSq5/G0n61TeLjP7dLWrnJu0v2Apwf8q0CVnA4YyHVTsQrz2v13icIIu35hTDbwpV7Bd8+vjtGE+87XHAXJMJ9+1V/WThnMTFIbRGMXDGul1GZw19A=,iv:V5dQxWYzSx62M0m3M7T+c09dyFGulVn546IJsBgIrDw=,tag:8qcV4gL8hJyhTPgCI0+7lA==,type:str]
secret_prometheus_remote_write:
    username: ENC[AES256_GCM,data:z1Pda2c=,iv:sbJPu2Ma7rZtLDxqxWkaAUNUDHHn8LSDsYCyxhtaI/8=,tag:jvdGibuw6UNiW0rnP1HRDg==,type:str]
    password: ENC[AES256_GCM,data:jd3TaA4=,iv:P648n+UN9/lD1W4XLzd0UNgQACS3HlbYzraDyifWh4w=,tag:16hIgHRwaWBKhPh0PxhL7Q==,type:str]
secret_nginx_shared_basic_auth:
    name: ""
    password: ""
secret_ethstats: ENC[AES256_GCM,data:6hXQvWNpetjdagA+c0Vz,iv:PB6KuyUwOmL+9wHPPKJNZncDENUg4yhGT+dRoh92Iho=,tag:ffyI0v3ovmJXCr+rY8nggA==,type:str]
secret_xatu_sentry:
    server_address: ENC[AES256_GCM,data:l228Fl+vT4QrHqQutB+JHA==,iv:6VjqEkfnu1/9PpB2UkGlDGLfDCxzaBqGwXQ0T+oVYe4=,tag:cWHUxmrt3e/dj5Kh4YTlDQ==,type:str]
    user: ENC[AES256_GCM,data:h5gs40s=,iv:lm7dsmNnF775z9XDvBec0pa0Rs0PNBIARdYBxoEym3M=,tag:G3RkpU4jM+ucXNGCbx2b7Q==,type:str]
    password: ENC[AES256_GCM,data:Bv5C8AE=,iv:gAkYt7nY6p2goaPUCq9NJ7uCMiuJVejyXkO2AEvbLJY=,tag:xDQ3cbU7ms57BXlP9OI+gA==,type:str]
secret_genesis_mnemonic: ENC[AES256_GCM,data:JYdCz0ECjGgeHkBdTuRz80abgv3fbqN0iJUT/kq6wWEh5ToyOZy0m0HQ+DErULO5ajrm61gdJ362gkwmc6GBcWi39OMtiAt2Zl2Xr+/MpUPdZenZ/+quWg0fm8P1S1UXF3H//IGsgCqn2NuKxZ4LstrWgTI10v3otOo9RRqnCz0q7obwCgl3BIenXvNrOM6O7yLIRuUp,iv:x5sf4Bi10mNvPAnadZ5kx73TrTMuEIBnS3yF4701ko8=,tag:+bQ5Y2pdViceIAx4Ynb9Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-12T14:00:07Z"
    mac: ENC[AES256_GCM,data:IOT7uNxSFqMGD7NZWWRa4frODrmb4GkAuGxBkFsyQaNpMc6rzzDOEihVxUyEx8VuvteauHluG434//vpeHmNWCYVjYqUHitJTT8eiwd9MCghigdHPflPCA4ywzjsmbeE93pfr03uFsEoeGYw5XeXUWRM3jlbTp17dUi+vGQPYz0=,iv:24kgSvcbsiWPWmbDqbHVaCqLuDVwWSUzSpI4/KCPJ2o=,tag:rnDDMUk6fZTDihQK+fadxg==,type:str]
    pgp:
        - created_at: "2024-03-12T14:00:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA1XtXDBHjv8wAQ/9F52BgajcW5cdkhf2vXu63HyaBbFaV/UGh1ADV6ULnbHR
            A0XrLvvEKVY4r5mx24frE4+EwzHfqNBUJZFkfpzeqDZD2wiZT+FX/Y/f/oAU8cB3
            UWV4zOkCQqNZozrMbCXLif1T/ScRYeGOQ0wmVMp+lZqW04BDxl4hdF7kqGnKrHOt
            l9yXcrbZMY7d+3drqAUOIof60+SZn8DaXfAq+xlNtgRQBAoZ2Djecb1hyPNlQoOk
            TESTXBSYAeeWYSEV1UOOLkgAl5kpZS4cXPhKpXolc88tuLrqK5rzf5veTdipMnML
            6rtNzZ8Kb6yndqWvH/UrAnaEto2rOsolSXVsbLej8vZrVvd21BcIO7EnJM/1Xcs2
            Xod2rhUluKPi6tZrMVBcKx5CbsHjG1dEAsWcxTGRFdw/02oM613D0ZpkDmiWkNNO
            6kWY46rTUNxcJqdJZEsEF6LXn98HVm4d8nsmdZ/gjQ+S+ou23gimof9VDoct3aAm
            4hmietWaGoXyYxcg2A5IbOHDb2275qpVdiyBcojnISXtbDSl8DEcZz/dxehn+hej
            WyTN9A8lwAHdjAb9FOtpJ9u+aCVx4eLXLB1aLztu29g3kr+hzSYCrgoMDKkSa9Jd
            xEw/Gq6DqgnJW/+WCC/FsWFblaVRdderb9byODraCvOkoLmyuE/D0BfTik0dFZzS
            XgE34G+IG2I1yvHt008NjHckJ+P6lenwEXTU70ba5tIks26Jf6t9DtAY4NRFvdXD
            eCD+i/5JTvsk9Lfez81cca4bqSlnr652r2tACi0cawLnxhbsa27UOGxUIuDMThk=
            =LHj1
            -----END PGP MESSAGE-----
          fp: CFD6E80BF0236ACBBE914A7B12A3D2D7D1ABCE65
    unencrypted_suffix: _unencrypted
    version: 3.8.1
